/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensureUiComponents() in @jupyterlab/buildutils */

import { createIcon } from './jlicon';
import { Icon } from './interfaces';

// icon svg import statements
import fileSvg from '../../style/icons/filetype/file.svg';
import folderSvg from '../../style/icons/filetype/folder.svg';
import html5Svg from '../../style/icons/filetype/html5.svg';
import imageSvg from '../../style/icons/filetype/image.svg';
import jsonSvg from '../../style/icons/filetype/json.svg';
import markdownSvg from '../../style/icons/filetype/markdown.svg';
import notebookSvg from '../../style/icons/filetype/notebook.svg';
import pythonSvg from '../../style/icons/filetype/python.svg';
import rKernelSvg from '../../style/icons/filetype/r-kernel.svg';
import reactSvg from '../../style/icons/filetype/react.svg';
import spreadsheetSvg from '../../style/icons/filetype/spreadsheet.svg';
import yamlSvg from '../../style/icons/filetype/yaml.svg';
import buildSvg from '../../style/icons/sidebar/build.svg';
import extensionSvg from '../../style/icons/sidebar/extension.svg';
import paletteSvg from '../../style/icons/sidebar/palette.svg';
import runningSvg from '../../style/icons/sidebar/running.svg';
import tabSvg from '../../style/icons/sidebar/tab.svg';
import jupyterFaviconSvg from '../../style/icons/splash/jupyter-favicon.svg';
import kernelSvg from '../../style/icons/statusbar/kernel.svg';
import lineFormSvg from '../../style/icons/statusbar/line-form.svg';
import listSvg from '../../style/icons/statusbar/list.svg';
import notTrustedSvg from '../../style/icons/statusbar/not-trusted.svg';
import terminalSvg from '../../style/icons/statusbar/terminal.svg';
import trustedSvg from '../../style/icons/statusbar/trusted.svg';
import addSvg from '../../style/icons/toolbar/add.svg';
import checkSvg from '../../style/icons/toolbar/check.svg';
import copySvg from '../../style/icons/toolbar/copy.svg';
import cutSvg from '../../style/icons/toolbar/cut.svg';
import pasteSvg from '../../style/icons/toolbar/paste.svg';
import refreshSvg from '../../style/icons/toolbar/refresh.svg';
import runSvg from '../../style/icons/toolbar/run.svg';
import saveSvg from '../../style/icons/toolbar/save.svg';
import stopSvg from '../../style/icons/toolbar/stop.svg';

// defaultIcons definition
export namespace IconImports {
  export const defaultIcons: ReadonlyArray<Icon.IModel> = [
    { name: 'file', svg: fileSvg },
    { name: 'folder', svg: folderSvg },
    { name: 'html5', svg: html5Svg },
    { name: 'image', svg: imageSvg },
    { name: 'json', svg: jsonSvg },
    { name: 'markdown', svg: markdownSvg },
    { name: 'notebook', svg: notebookSvg },
    { name: 'python', svg: pythonSvg },
    { name: 'r-kernel', svg: rKernelSvg },
    { name: 'react', svg: reactSvg },
    { name: 'spreadsheet', svg: spreadsheetSvg },
    { name: 'yaml', svg: yamlSvg },
    { name: 'build', svg: buildSvg },
    { name: 'extension', svg: extensionSvg },
    { name: 'palette', svg: paletteSvg },
    { name: 'running', svg: runningSvg },
    { name: 'tab', svg: tabSvg },
    { name: 'jupyter-favicon', svg: jupyterFaviconSvg },
    { name: 'kernel', svg: kernelSvg },
    { name: 'line-form', svg: lineFormSvg },
    { name: 'list', svg: listSvg },
    { name: 'not-trusted', svg: notTrustedSvg },
    { name: 'terminal', svg: terminalSvg },
    { name: 'trusted', svg: trustedSvg },
    { name: 'add', svg: addSvg },
    { name: 'check', svg: checkSvg },
    { name: 'copy', svg: copySvg },
    { name: 'cut', svg: cutSvg },
    { name: 'paste', svg: pasteSvg },
    { name: 'refresh', svg: refreshSvg },
    { name: 'run', svg: runSvg },
    { name: 'save', svg: saveSvg },
    { name: 'stop', svg: stopSvg }
  ];
}

// wrapped icon definitions
export const FileIcon = createIcon('file', fileSvg);
export const FolderIcon = createIcon('folder', folderSvg);
export const Html5Icon = createIcon('html5', html5Svg);
export const ImageIcon = createIcon('image', imageSvg);
export const JsonIcon = createIcon('json', jsonSvg);
export const MarkdownIcon = createIcon('markdown', markdownSvg);
export const NotebookIcon = createIcon('notebook', notebookSvg);
export const PythonIcon = createIcon('python', pythonSvg);
export const RKernelIcon = createIcon('r-kernel', rKernelSvg);
export const ReactIcon = createIcon('react', reactSvg);
export const SpreadsheetIcon = createIcon('spreadsheet', spreadsheetSvg);
export const YamlIcon = createIcon('yaml', yamlSvg);
export const BuildIcon = createIcon('build', buildSvg);
export const ExtensionIcon = createIcon('extension', extensionSvg);
export const PaletteIcon = createIcon('palette', paletteSvg);
export const RunningIcon = createIcon('running', runningSvg);
export const TabIcon = createIcon('tab', tabSvg);
export const JupyterFaviconIcon = createIcon(
  'jupyter-favicon',
  jupyterFaviconSvg
);
export const KernelIcon = createIcon('kernel', kernelSvg);
export const LineFormIcon = createIcon('line-form', lineFormSvg);
export const NotTrustedIcon = createIcon('not-trusted', notTrustedSvg);
export const TerminalIcon = createIcon('terminal', terminalSvg);
export const TrustedIcon = createIcon('trusted', trustedSvg);
export const AddIcon = createIcon('add', addSvg);
export const CopyIcon = createIcon('copy', copySvg);
export const CutIcon = createIcon('cut', cutSvg);
export const PasteIcon = createIcon('paste', pasteSvg);
export const RefreshIcon = createIcon('refresh', refreshSvg);
export const RunIcon = createIcon('run', runSvg);
export const SaveIcon = createIcon('save', saveSvg);
export const StopIcon = createIcon('stop', stopSvg);
