/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @jupyterlab/buildutils */
import '@lumino/widgets/style/index';
import '@jupyterlab/ui-components/style/index';
import '@jupyterlab/apputils/style/index';
import '@lumino/dragdrop/style/index';
import '@jupyterlab/codeeditor/style/index';
import '@jupyterlab/statusbar/style/index';
import '@jupyterlab/rendermime/style/index';
import '@jupyterlab/docregistry/style/index';
import '@jupyterlab/cells/style/index';

import './base.css';
