/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @jupyterlab/buildutils */
import '@jupyterlab/ui-components/style/index';
import '@jupyterlab/rendermime/style/index';
import '@jupyterlab/application/style/index';
import '@jupyterlab/docmanager/style/index';
import '@jupyterlab/fileeditor/style/index';
import '@jupyterlab/markdownviewer/style/index';
import '@jupyterlab/notebook/style/index';
import '@jupyterlab/toc/style/index';
