/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @jupyterlab/buildutils */
import '@jupyterlab/codeeditor/style/index.js';
import '@jupyterlab/statusbar/style/index.js';
import '@jupyterlab/codemirror/style/index.js';
import '@jupyterlab/docregistry/style/index.js';
import '@jupyterlab/application/style/index.js';
import '@jupyterlab/fileeditor/style/index.js';
import '@jupyterlab/mainmenu/style/index.js';
