version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
    nodejs: latest
  jobs:
    install:
      - python -m pip install --upgrade pip
      - python -m pip install --group 'docs'
    post_install:
      # this should have already run, but show some errors/warnings more cleanly
      - jlpm
      # again ensure all packages are built
      - jlpm build:packages
      # avoid the lengthy `typedoc` build inside `sphinx` for cleaner logs
      - jlpm docs

sphinx:
  configuration: docs/source/conf.py
