enableImmutableInstalls: false

enableInlineBuilds: false

enableTelemetry: false

httpTimeout: 60000

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

yarnPath: ./jupyterlab/staging/yarn.js
