/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @jupyterlab/buildutils */
import '@jupyterlab/ui-components/style/index';
import '@jupyterlab/apputils/style/index';
import '@jupyterlab/application/style/index';
import '@jupyterlab/extensionmanager/style/index';
import '@jupyterlab/mainmenu/style/index';
