/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @jupyterlab/buildutils */
import '@lumino/widgets/style/index';
import '@jupyterlab/apputils/style/index';
import '@jupyterlab/statusbar/style/index';
import '@jupyterlab/docregistry/style/index';
import '@jupyterlab/application/style/index';
import '@jupyterlab/docmanager/style/index';
import '@jupyterlab/mainmenu/style/index';
