/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @jupyterlab/buildutils */
import '@lumino/widgets/style/index';
import '@jupyterlab/ui-components/style/index';
import '@jupyterlab/apputils/style/index';
import '@jupyterlab/statusbar/style/index';
import '@jupyterlab/rendermime/style/index';
import '@jupyterlab/application/style/index';
import '@jupyterlab/logconsole/style/index';
import '@jupyterlab/mainmenu/style/index';
import '@jupyterlab/notebook/style/index';

import './base.css';
