/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @jupyterlab/buildutils */
import '@lumino/widgets/style/index';
import '@jupyterlab/apputils/style/index';
import '@jupyterlab/codeeditor/style/index';
import '@jupyterlab/statusbar/style/index';
import 'codemirror/lib/codemirror';
import 'codemirror/addon/dialog/dialog';
import 'codemirror/addon/fold/foldgutter';

import './base.css';
