/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @jupyterlab/buildutils */
import '@lumino/widgets/style/index';
import '@jupyterlab/ui-components/style/index';
import '@jupyterlab/apputils/style/index';
import '@jupyterlab/codeeditor/style/index';
import 'codemirror/lib/codemirror';
import '@jupyterlab/codemirror/style/index';
import '@jupyterlab/docregistry/style/index';
import '@jupyterlab/application/style/index';
import '@jupyterlab/cells/style/index';
import '@jupyterlab/console/style/index';
import '@jupyterlab/fileeditor/style/index';
import '@jupyterlab/notebook/style/index';

import './base.css';
