/* eslint-disable */

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jlpm build:schema to regenerate this file.
 */

/**
 * When multiple servers match specific document/language, the server with the highest priority will be used
 */
export type PriorityOfTheServer = number;
/**
 * Whether to ask server to send logs with execution trace (for debugging). To see these messages, set loggingLevel to debug or log. Accepted values are: "off", "messages", "verbose". Servers are allowed to ignore this request.
 */
export type AskServersToSendTraceNotifications = 'off' | 'messages' | 'verbose';

/**
 * Language Server Protocol settings.
 */
export interface LanguageServer {
  language_servers?: LanguageServer1;
  setTrace?: AskServersToSendTraceNotifications;
  [k: string]: any;
}
/**
 * Language-server specific configuration, keyed by implementation
 */
export interface LanguageServer1 {
  [k: string]: LanguageServer2;
}
/**
 * This interface was referenced by `LanguageServer1`'s JSON-Schema definition
 * via the `patternProperty` ".*".
 *
 * This interface was referenced by `LanguageServer`'s JSON-Schema
 * via the `definition` "language-server".
 */
export interface LanguageServer2 {
  serverSettings?: LanguageServerConfigurations;
  priority?: PriorityOfTheServer;
  [k: string]: any;
}
/**
 * Configuration to be sent to language server over LSP when initialized: see the specific language server's documentation for more
 */
export interface LanguageServerConfigurations {
  [k: string]: any;
}
