// Copyright (c) Jupyter Development Team.
// Distributed under the terms of the Modified BSD License.

module.exports = [
  require('../../lib/about/plugin').plugin,
  require('../../lib/application/plugin').plugin,
  require('../../lib/clipboard/plugin').plugin,
  require('../../lib/codemirror/plugin').editorServices,
  require('../../lib/codemirror/plugin').editorCommands,
  require('../../lib/commandlinker/plugin').plugin,
  require('../../lib/commandpalette/plugin').plugin,
  require('../../lib/console/plugin').plugin,
  require('../../lib/console/codemirror/plugin').plugin,
  require('../../lib/csvwidget/plugin').plugin,
  require('../../lib/docmanager/plugin').plugin,
  require('../../lib/docregistry/plugin').plugin,
  require('../../lib/editorwidget/plugin').plugin,
  require('../../lib/faq/plugin').plugin,
  require('../../lib/filebrowser/plugin').plugin,
  require('../../lib/help/plugin').plugin,
  require('../../lib/imagewidget/plugin').plugin,
  require('../../lib/inspector/plugin').plugin,
  require('../../lib/landing/plugin').plugin,
  require('../../lib/launcher/plugin').plugin,
  require('../../lib/layoutrestorer/plugin').plugin,
  require('../../lib/mainmenu/plugin').plugin,
  require('../../lib/markdownwidget/plugin').plugin,
  require('../../lib/notebook/plugin').plugin,
  require('../../lib/notebook/codemirror/plugin').plugin,
  require('../../lib/rendermime/plugin').plugin,
  require('../../lib/running/plugin').plugin,
  require('../../lib/services/plugin').plugin,
  require('../../lib/shortcuts/plugin').plugin,
  require('../../lib/statedb/plugin').plugin,
  require('../../lib/terminal/plugin').plugin
];
