#!/usr/bin/env bash

# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

source activate ${NB_PYTHON_PREFIX}

set -euxo pipefail

# pre-install nodejs deps outside of editable python install
yarn
yarn build:prod:minimize

# use conda-managed versions for all deps
pip install -vv -e .[dev] --no-build-isolation

# use a well-known location
mkdir -p ~/.jupyter/
cp binder/jupyter_config.py ~/.jupyter/

# until jupyter-server is the default on binder
cp ${NB_PYTHON_PREFIX}/bin/jupyter-lab ${NB_PYTHON_PREFIX}/bin/jupyter-notebook

# emit
jupyter troubleshoot
jupyter notebook --show-config
jupyter lab --show-config
jupyter labextension list
jupyter server extension list
