#!/bin/bash
set -euo pipefail

pip install -e .
pip install -U notebook

jlpm

jlpm build

# This seems to be explicitly needed with `pip install -e .`
jupyter serverextension enable jupyterlab --sys-prefix
