#!/usr/bin/env python3
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

import os
import shutil
import sys

argv = sys.argv[1:] + [
    "--debug",
    "--dev-mode",
    "--extensions-in-dev-mode",
    "--collaborative",
    "--ContentsManager.allow_hidden=True",
    # Use advance file ID service for out of band rename support
    "--FileIdExtension.file_id_manager_class=jupyter_server_fileid.manager.LocalFileIdManager",
    "--config",
    "binder/jupyter_notebook_config.py",
]
print(argv)  # noqa


# Convert from jupyter-notebook based to jupyter-lab based start-up
def nb2jps(s):
    return s.replace("jupyter-notebook", "jupyter-lab").replace("--NotebookApp.", "--ServerApp.")


new_argv = list(map(nb2jps, argv.copy()))
print(new_argv)  # noqa

with open(".startup_args.txt", "w") as fid:
    fid.write(str(new_argv))

os.execv(shutil.which(new_argv[0]), new_argv)
