#!/usr/bin/env python3
import os
import shutil
import sys

argv = sys.argv[1:] + ['--config', 'binder/jupyter_notebook_config.py']
print(argv)

with open('startup_args.txt', 'w') as fid:
    fid.write(str(argv))

os.execv(shutil.which(argv[0]), argv)
