name: Update PR comment with UI test report

on: # zizmor: ignore[dangerous-triggers] required to post report from workflow_run artifact to PR comment
  workflow_run:
    workflows: ["UI Tests"]
    types: [completed]

jobs:
  update-preview-comment:
    name: Add report link to preview comment
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      pull-requests: write
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/ui-test-report-comment@21b1cac622018fd37ec13a1c8081da814e10d94e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          report_line_prefix: "View the integration tests report in the browser: "
